From ubuntu:14.04

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:ondrej/php5-oldstable && \
    add-apt-repository ppa:sergey-dryabzhinsky/php53